### ISSUE TITLE
Using in an each block

### ISSUE THREAD

**Issue by neverfox** [GavinJoyce/ember-component-inbound-actions#11]
Given that this requires setting actionReceiver, how would you make this work when the component is repeated in an each block and you want the event to go to a specific instance of the component?

**Comment by anujku** [comment]
<pre>
{{#each in counter}}
  {{name-form actionReceiver=createNameUsingHandlebar counter.id}}
{{/each}}
</pre>

**Comment by joukevandermaas** [comment]
```hbs
{{#each model as |item|}}
  {{my-component actionReceiver=item.actionReceiver}}
{{/each}}
```
