### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by YoranBrondsema** [GavinJoyce/ember-component-inbound-actions#14]
Hi,

I'm developing an addon that is dependent on `ember-component-inbound-actions` so I am relying on PR #12 (https://github.com/GavinJoyce/ember-component-inbound-actions/pull/12) as I don't want prototype extensions enabled in my addon. However, the latest release 0.0.4 does not incorporate this PR. I can point to a specific commit in my `package.json` but that is not so clean.

Would it be possible to release a new version that includes the latest PRs?

Thanks!

**Comment by GavinJoyce** [comment]
I just released `1.0.0` :cake:

**Comment by YoranBrondsema** [comment]
Awesome, thanks!
