### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by anehx** [GavinJoyce/ember-component-inbound-actions#30]
Could you release a new version containing #29, so we can get rid of the annoying babel deprecation warning?

**Comment by alechirsch** [comment]
+1

**Comment by pkmh** [comment]
+1

**Comment by jewls618** [comment]
+1

**Comment by MatthewParke** [comment]
+1

**Comment by gmarkv10** [comment]
+1

**Comment by GavinJoyce** [comment]
Sorry for the delay, thanks for the ping:

https://github.com/GavinJoyce/ember-component-inbound-actions/releases/tag/v1.3.0
