### ISSUE TITLE
nameForm undefined

### ISSUE THREAD

**Issue by oskarrough** [GavinJoyce/ember-component-inbound-actions#4]
Hi, this is probably my mistake but couldn't get it to work. Whenever I do `this.get('nameForm').send('something')`, I get `Cannot read property 'send' of undefined`.

I can inspect the actionReciever property on my component but see no nameForm on my controller. What did I miss?

``` JavaScript
// index.hbs
{{ember-youtube title=model.title actionReciever=nameForm}}

// components/my-component.js
import InboundActions from 'ember-component-inbound-actions/inbound-actions';
export default Ember.Component.extend(InboundActions, {
```

**Comment by zardaloop** [comment]
I know this issue is closed and is an old issue. However if in case someone like me wants to use it in the route rather than component, don't forget to bind it to the model.nameForm. I always forget that :)
