### ISSUE TITLE
Ember 1.13 compatability

### ISSUE THREAD

**Issue by oskarrough** [GavinJoyce/ember-component-inbound-actions#6]
Hi, having trouble making this approach work with Ember 1.13. Tried to build a similar approach here with two test cases:

http://stackoverflow.com/questions/30274097/sending-actions-to-a-component-with-ember-js-1-13

- Working example Ember 1.12: http://emberjs.jsbin.com/wokelikice/1/edit
- Failing example Ember 1.13: http://jsbin.com/yaporapuwu/2/edit

**Comment by GavinJoyce** [comment]
This seems to do it: https://github.com/GavinJoyce/ember-component-inbound-actions/pull/8/files#diff-7115e0b52d19307a1e1ca44560b1178dR6

**Comment by digitalbreed** [comment]
I can confirm that this seems to do the trick. Any idea when this will be available as a new version? Currently including the branch, would rather like to point to a new release.

**Comment by GavinJoyce** [comment]
@digitalbreed Perhaps you could cut a PR?

**Comment by matthias-k** [comment]
@GavinJoyce I created a new pull request by rebasing the branch on top of master: #10.
